[project]
name = "stack"
version = "0.1.0"
description = "Full Stack ML"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/stack"]